Fix com.jetbrains.JBR: can't find referenced method
After https://github.com/JetBrains/compose-multiplatform-core/pull/2097 is merged, CI fails with:
```
Warning: com.jetbrains.JBR: can't find referenced method 'java.lang.Object invokeExact(java.lang.Class,java.lang.Class,java.lang.Class,java.lang.Class,java.util.Map,java.util.function.Function)' in library class java.lang.invoke.MethodHandle
Warning: com.jetbrains.JBR: can't find referenced method 'java.lang.Object invokeExact(java.lang.invoke.MethodHandles$Lookup)' in library class java.lang.invoke.MethodHandle
<============-> 96% EXECUTING [3s]                                           Warning: there were 2 unresolved references to library class members.aseJars
         You probably need to update the library versions.-crash-in-the-field
         (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedlibraryclassmember)
Unexpected error
java.io.IOException: Please correct the above warnings first.
```

During Gradle tests.

## Testing
Tests for Gradle plugin pass

## Release Notes
### Fixes - Desktop
N/A