Revert "Fix signing settings when no Keychain is specified (#1093)"
This reverts commit 5b34141cbe40a269ddc38151da0d111d1a5cf0f4.

We have a compilation error:
```
e: /mnt/agent/work/737a92a2f69083c2/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/validation/ValidatedMacOSSigningSettings.kt: (59, 20): Unresolved reference: keychainFile
```