[gradle] Downgrade gradle in tests to 8.3 because of issue on Windows
It fails DesktopApplicationTest.proguard test on Windows:
Execution failed for task ':createReleaseDistributable'.
> java.io.IOException: Unable to delete directory 'C:\Users\runneradmin\AppData\Local\Temp\junit15199828818905379674\build\compose\binaries\main-release\app'
Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
- C:\Users\runneradmin\AppData\Local\Temp\junit15199828818905379674\build\compose\binaries\main-release\app\simple\simple.exe
- C:\Users\runneradmin\AppData\Local\Temp\junit15199828818905379674\build\compose\binaries\main-release\app\simple

More info: https://github.com/gradle/gradle/issues/26912