Telling Doclava to target Java 8 for generateSdkApi
This prevents it from displaying warnings that look like this:

  androidx-platform-dev/out/androidx/build/tmp/expandedArchives/android-stubs-src.jar_b031e52b8c48503b817e05353c0f8501/java/io/BufferedInputStream.java:28: error: package exists in another module: java.base
  package java.io;
  ^

Bug: 154755010

Test: ./cleanBuild.sh -y generateSdkApi # and notice that there are no warnings saying "error: package exists in another module"

Test: run `./gradlew generateSdkApi` before and after this change, diff -r out-*/androidx/build/javadoc/release/sdk_current.txt, and see that the change is this:
      One addition of "method protected deprecated void finalize() throws java.lang.Throwable;"
      Lots of removals of "method protected void finalize() throws java.lang.Throwable;"
    Which seems reasonable because the `finalize` method was not deprecated in Java 8 but was deprecated in Java 11

Change-Id: I143fdc46e32041d614e6d38633351c4d4bbbdf42