Fix Proguard error on CI
The error:
```
java.io.IOException: Please correct the above warnings first.
```
https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_Publish_2_AllGitHubRelease/4312357?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true&showLog=4312349_1096_787&logFilter=debug&logView=flowAware

Regression after https://github.com/JetBrains/compose-multiplatform/pull/3628

We don't need `implementation` here, `compileOnly` works for our case