Fix crash on Windows
java.io.IOException: Cannot run program "C:\Program": CreateProcess error=2, The system cannot find the file specified
 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
 at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewManagerImpl.runPreviewThread$lambda-1$startPreviewProcess(PreviewManager.kt:74)
 at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewManagerImpl.access$runPreviewThread$lambda-1$startPreviewProcess(PreviewManager.kt:44)
 at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewManagerImpl$special$$inlined$repeatWhileAliveThread$default$1.invoke(PreviewManager.kt:262)
 at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewManagerImpl$special$$inlined$repeatWhileAliveThread$default$1.invoke(PreviewManager.kt:239)
 at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
 at java.base/java.lang.ProcessImpl.create(Native Method)
 at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
 at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
 ... 6 more