Fix "gradle-plugins/compose/build/test-summary'. No such file" (#5578)
Fixes
https://github.com/JetBrains/compose-multiplatform/actions/runs/24189409833/job/70629381414?pr=5577:

> test-gradle-plugin (macos-15-xlarge, 8.13, 9.0.0)
```
Run for SUMMARY_FILE in `find . -name "*.md"`; do
Error: An error occurred trying to start process '/bin/bash' with working directory '/Users/runner/work/compose-multiplatform/compose-multiplatform/gradle-plugins/compose/build/test-summary'. No such file or directory
```

The reason is that Gradle runs the test task from cache:
```
> Task :compose:test FROM-CACHE
```

This PR makes tests always run

## Release Notes
N/A