Fix validation errors after updating TeamCity base image (#5587)
```
org.gradle.jvm.toolchain.internal.install.exceptions.ToolchainProvisioningException: Cannot find a Java installation on your machine (Linux 5.15.0-1084-aws amd64) matching: {languageVersion=17, vendor=any vendor, implementation=vendor-specific}. Some toolchain resolvers had internal failures: foojay (Requesting vendor list failed: {
  "result":[],
  "message":"There was an internal error and the pkg cache is currently be restored, please try again later"
}).
```

- Use `jvmTarget` instead of `jvmToolchain` to build the project without
JDK 17 installed (only with JDK 21)
- Update `org.gradle.toolchains.foojay-resolver-convention` to a stable
version

## Release Notes
N/A